export const REPOSITORIES_FETCH_FAILURE = 'REPOSITORIES_FETCH_FAILURE';
export const REPOSITORIES_FETCH_REQUEST = 'REPOSITORIES_FETCH_REQUEST';
export const REPOSITORIES_FETCH_SUCCESS = 'REPOSITORIES_FETCH_SUCCESS';
